### ISSUE TITLE
Walk through guide for using Connect Webviews

### ISSUE THREAD

**Issue by dawnho** [seamapi/api-docs#125]
We want to create a step-by-step guide [using this template](https://github.com/seamapi/api-docs/blob/main/north-star-docs/TEMPLATE.md):
* How to generate a Connect Webview?
  * Where can they get access to the list of `accepted_providers`?
  * Can they get a list of all `lock` providers? What about `stable` providers?
* Best practices for incorporating a webview into your app
  * Adding it with a redirect, adding it via an iframe
  * When to generate a new connect webview (every time the add account button is clicked)
* How do you customize a Connect Webview?
* How does the `custom_redirect_url` work? Can they replace the success screen at the end?
* How do you map an end user who has logged in through a webview with the connected account that was created?
* When do devices on a new connected account get synced? How do we detect that?
* How do we detect when logins have failed, which provider were they using when that failure happened?

[Areas of Confusion from Customer Convos](https://www.notion.so/2023-07-09-Customer-Slack-Summaries-a1972913a48442ac8f7183534327bb61):
- How to get list of supported brands
- How to figure out which connected account is associated with a customer after they complete the webview process
- Whether `custom_redirect_url` replaces the success screen
- How to use the `connected_account.connected` event
- Should they generate a connect webview per brand? (Answer: No)
- Whether or not they have to delete a connect webview when a user deletes a device
- What to do when an account has been connected, and but some of the devices were paired with another account?

**Comment by razor-x** [comment]
* How to generate a Connect Webview?
  * Where can they get access to the list of `accepted_providers`?
    - TBD in https://github.com/seamapi/seam-connect/pull/3614/files#r1261820652
