### ISSUE TITLE
Walk through guide on implementing lock / unlock

### ISSUE THREAD

**Issue by dawnho** [seamapi/api-docs#128]
We want to create a step-by-step guide [using this template](https://github.com/seamapi/api-docs/blob/main/north-star-docs/TEMPLATE.md):
- How to detect whether a lock is locked / unlocked
- How to trigger a lock / unlock action
- How to confirm that a lock / unlock has occurred? What are the best practices there?

[Areas of Confusion from Customer Convos](https://www.notion.so/2023-07-09-Customer-Slack-Summaries-a1972913a48442ac8f7183534327bb61):
- Does an action attempt success mean that the lock has unlocked? (No)
- When does the lock unlock property sync after the action is triggered?
- Is the `lock.locked` or `lock.unlocked` webhook always triggered?
- How do the event logs for lock unlocks work, are they reliable?

**Comment by seveibar** [comment]
https://github.com/seamapi/public-tracker/issues/1
