### ISSUE TITLE
discrepancy between connected_account events in Seam API docs and a real state I see in the Svix dashboard.

### ISSUE THREAD

**Issue by seveibar** [seamapi/api-docs#13]
In docs we have connected_account.added but connected_account.created in the Svix.

![image](https://user-images.githubusercontent.com/1910070/217894747-4a28b607-cd8b-408b-90f5-95fd2a41d63c.png)
![image](https://user-images.githubusercontent.com/1910070/217894775-65e4e97b-322f-46cd-9f40-bd1e3995b495.png)

https://hello-seam.slack.com/archives/C04EY04BTJ4/p1675930670666479

**Comment by itelo** [comment]
@seveibar It's already solved in https://github.com/seamapi/api-docs/pull/12/files
