### ISSUE TITLE
Walk through guide on Device Management

### ISSUE THREAD

**Issue by dawnho** [seamapi/api-docs#131]
We want to create a step-by-step guide [using this template](https://github.com/seamapi/api-docs/blob/main/north-star-docs/TEMPLATE.md):
* How managed and unmanaged devices work
* What is the difference between unmanaging a device v.s. deleting it?
* What happens when you unmanage a device? How about the access codes and climate schedules that are attached to it?
* How device deletions work, do they get added when an account syncs again?
* How to reconnect a device if it has ben removed

Areas of Confusion:
* What endpoints do you use to get the managed or unmanaged device lists?
* What webhook events get sent when a device is newly registered or converted to unmanaged?
* Are devices managed or unmanaged when they are first added from a connect webview?

**Comment by razor-x** [comment]
Ref this accepted RFC for changes to device deletion behavior: https://github.com/seamapi/rfc/blob/main/rfcs/2023-03-08-unmanaged-devices.md#changes-to-existing-behavior

> ## Changes to existing behavior
> - Deleting a device:
>   - Before: `DELETE /devices/delete` removes `seam.device`, all access codes, and all action attempts, but retains `seam.third_party_device`.
>     The device is no longer synced, no longer visible to the user, and the user cannot restore the device without resetting the connected account.
>   - After: `DELETE /devices/delete` and `DELETE /devices/unmanaged/delete` removes the device and all references: the third party device, access codes, and action attempts.
>     If the device is still on the third party account (or re-added later), the device will appear again as a (new) managed device.
> - For each `third_party_device` with no matching `seam.device`, on the next sync,
>   each device will either be re-added as `unmanaged` if found, or fully deleted otherwise.

**Comment by dawnho** [comment]
@abimaelmartell, max had some extra time, so he volunteered to take this on

**Comment by seveibar** [comment]
Point of clarity:
When a device is deleted:
* unmanage the codes
* Run a cleanup in the background that cleans up the codes Seam created later (no guarantees about when)

There's a good reason we do it this way- we can't guarantee the deletion, so customers that want to provide that guarnantee SHOULDNT unmanage without cleaning up themselves
e.g. a common scenario will be unmanaging a device that is offline
