### ISSUE TITLE
Generate all properties of an API endpoint using OpenAPI and Insertion Tags

### ISSUE THREAD

**Issue by seveibar** [seamapi/api-docs#188]
We want to automatically generate docs for API endpoints, particularly the properties table as shown below:

![image](https://github.com/seamapi/api-docs/assets/1910070/ed40b532-06c0-4db3-ade5-156b653e6007)

Whenever someone puts the following in an `*.md` file, after running `run-doc-snippet-bot.sh` it should be replaced with a property table using the openapi at https://connect.getseam.com/openapi.json

**BEFORE**:

```
...

<!-- INJECT PROPERTIES /access_codes/create !-->

...
```

**AFTER**:

```
...

<!-- INJECT PROPERTIES START /access_codes/create --!>
| `device_id` | type: string                 | ID of Device                           |
| `name`       | type: string\nOptional | From when is the code valid  |
<!-- INJECT PROPERTIES END --!> 
...

...
```

Do each of the following in separate PRs:

1. Add directory `doc-snippet-bot` and run `npm init -y` and `npm add esbuild esbuild-runner` `npm add -D ava`
2. Introduce a test that shows that the doc snippet generator works
3. Add a script `run-doc-snippet-bot.sh` (like [run-code-snippet-bot.sh](https://github.com/seamapi/api-docs/blob/main/run-snippet-bot.sh)) that runs the doc snippet generator on the docs directory

## Implementation Notes

* If you run the program again, it should update any previous generated INJECT PROPERTIES by searching for INJECT PROPERTIES START/END
* code-snippet-bot has the most code conventions, use it as a reference for various conventions
* Don't overwrite descriptions that are already in a table, a writer may fill in descriptions after generation

**Comment by kainpets** [comment]
The actual properties that need to be fetched depend on the content of the *.md file? Per example: the bot returns properties located inside the requestBody of  /access_codes/create endpoint? 

The bot shouldn't return rigidly specified data all the time but parse the user's input for correct endpoint and fetch the part of data according to the provided input?

![Screenshot from 2023-10-05 23-00-16](https://github.com/seamapi/api-docs/assets/41388251/9f4fe963-3ef1-48c8-b942-0b7e8d4a708d)
